#!/bin/bash
echo "NOTE: RUN this file in mnt folder only"
phase=$( date | tr -d ' ' )
mkdir curl/$phase 
cp output/fetcher.py /home/spider/production/veetwo/veetwo/lib/jobs/fetcher.py
cd curl/$phase
echo "Fetching urls"
mysql -uroot -h10.241.31.96 spider -e "select distinct rdomain, uid, url, product_id from url_queue where is_disabled=0 and last_fetch=0" >> "urls";
echo " Fetching domains"
mysql -uroot -h10.241.31.96 spider -e "select distinct rdomain from url_queue where is_disabled=0 and last_fetch=0" >> "domains"
echo "Creating directories"
mkdir input
echo "Starting converter"
python converter.py 
echo "Starting Crawler"
python fetcher.py
cp urls output/urls
python upload.py
python query.py
mysql -uroot -h10.241.31.96 spider < query
sed -i 's/phase = str(phase)/phase = str('$phase')/g' /home/spider/production/veetwo/veetwo/lib/jobs/fetcher.py
cd /home/spider/production/veetwo
paster job_runner --configuration-file machine/ec2/spider/ini/spider.ini --job-name=fetcher:Starter&
